Differential team
david-fisher/320-F20-Track-II pull request #218
Opened 2020-12-03 01:41 UTC by rlee287

2020-12-03 20:21 UTC, agalperina commented
Action endpoints are working fine on my end.

2020-12-03 21:06 UTC, thuang814 commented
![image](https://user-images.githubusercontent.com/17036217/101088249-5fd85b00-3581-11eb-9e45-fd3faefbd262.png)
I am currently getting this error when I run the put request for scenarios/stakeholders

2020-12-03 21:10 UTC, thuang814 commented
![image](https://user-images.githubusercontent.com/17036217/101088629-f9a00800-3581-11eb-8e05-292a73adf930.png)
I am also getting this error when calling scenarios/stakeholders/conversation

2020-12-03 21:52 UTC, rasdy requested changes

2020-12-03 21:52 UTC, rasdy commented on goon-universe/queries.js
> +}
These functions are being called in app.js as `getInitActionResponse(studentID, scenarioID, function(result)`

Are there query functions that app.js can use to get the submissionID and questionID? If not, this should be re-written to take in a studentID and scenarioID.

2020-12-04 00:35 UTC, rlee287 commented
Notes from @thuang814 : get functions fixed but add function is still broken

2020-12-04 05:35 UTC, aj8uppal approved these changes

2020-12-04 05:35 UTC, thuang814 approved these changes

2020-12-04 05:36 UTC, rasdy approved these changes

2020-12-04 05:37 UTC, merged